### ISSUE TITLE
No coco

### ISSUE THREAD

**Issue by sunqimin** [MIV-XJTU/ARTrack#90]
你好！请问如果不使用coco数据集的话是不是只需要训练一次就可以了，那这里的config是怎么设置呢？

**Comment by AlexDotHam** [comment]
分两个阶段主要是加速训练，一阶段的训练比较快容易收敛，二阶段的速度慢，我没有尝试过只使用二阶段是否能收敛，我认为应该还是比较困难的。

**Comment by sunqimin** [comment]
可以分享一下两个阶段训练的loss吗，我感觉我这里好像是有问题的

**Comment by AlexDotHam** [comment]
[artrackv2-artrackv2_256_got.log](https://github.com/user-attachments/files/17742774/artrackv2-artrackv2_256_got.log)
[artrackv2_seq-artrackv2_seq_256_got.log](https://github.com/user-attachments/files/17742776/artrackv2_seq-artrackv2_seq_256_got.log)
That will be my pleasure

**Comment by sunqimin** [comment]
Traceback (most recent call last):
  File "D:\SQM\ARTrack-main\lib\train\../..\lib\train\trainers\base_trainer.py", line 85, in train
    self.train_epoch()
  File "D:\SQM\ARTrack-main\lib\train\../..\lib\train\trainers\ltr_seq_trainer.py", line 227, in train_epoch
    self.cycle_dataset(loader)
  File "D:\SQM\ARTrack-main\lib\train\../..\lib\train\trainers\ltr_seq_trainer.py", line 83, in cycle_dataset
    explore_result = self.actor.explore(data)
  File "D:\SQM\ARTrack-main\lib\train\../..\lib\train\actors\artrack_seq.py", line 472, in explore
    outputs_template = self.batch_init(template, template_bbox, here_gt_bbox)
  File "D:\SQM\ARTrack-main\lib\train\../..\lib\train\actors\artrack_seq.py", line 325, in batch_init
    self.channel_average.append(np.mean(img, axis=(0, 1)))
  File "<__array_function__ internals>", line 180, in mean
  File "C:\Users\Mylog06\.conda\envs\artrack\lib\site-packages\numpy\core\fromnumeric.py", line 3432, in mean
    return _methods._mean(a, axis=axis, dtype=dtype,
  File "C:\Users\Mylog06\.conda\envs\artrack\lib\site-packages\numpy\core\_methods.py", line 168, in _mean
    rcount = _count_reduce_items(arr, axis, keepdims=keepdims, where=where)
  File "C:\Users\Mylog06\.conda\envs\artrack\lib\site-packages\numpy\core\_methods.py", line 76, in _count_reduce_items
    items *= arr.shape[mu.normalize_axis_index(ax, arr.ndim)]
numpy.AxisError: axis 0 is out of bounds for array of dimension 0
你好！请问在第二阶段第一个epoch训练结束之后报错该怎么解决呢

**Comment by AlexDotHam** [comment]
Emm，我这个代码我从来没在Windows上跑过，这个问题我也不太了解，不过看起来可能是Numpy版本的问题，建议你尝试一下1.23或者更低的版本，您可以在之后告知我结果。
另外，如果您是在特定的某个iteration才会报错的话，我猜测可能是数据集的原因，TrackingNet存在一些非法数据，这些数据的读取可能是错误的原因，您可以在”"D:\SQM\ARTrack-main\lib\train../..\lib\train\actors\artrack_seq.py", line 325, in batch_init“
这一行附近增加一个try，如果读取到潜在的非法数据直接return，形如该文件中491行的对应代码

**Comment by AlexDotHam** [comment]
您还可以参考：
https://github.com/MIV-XJTU/ARTrack/issues/36
他和您有相似的问题。

**Comment by sunqimin** [comment]
我的问题依然没有解决，我猜是loader的原因，因为数据是一样的，而第一阶段和第二阶段不一样的地方就在于这里，所以请问为什么第一阶段和第二阶段的loader不一样呢

**Comment by AlexDotHam** [comment]
loader的不同是来源于：


一阶段的训练实际上是帧间的模板匹配，它通过随机采样一个视频序列的两帧，来进行训练，但这样的训练方式与追踪的真实流程不同。举个例子，再我们推理时，我们实际上是从第一帧开始逐帧的推理之后的每一帧，每一帧的推理结果都会影响接下来的每一帧的推理，然而在训练时这个过程被忽略了。

因此我们引入二阶段推理，他通过采样一个视频中的连续N帧来进行训练，从第一帧开始逐帧推理到最后一帧，最后进行以此反向传播，这样的方式显然对齐了训练与推理，然而其数据采样方式的不同和数据增强的不同使我们使用了两种不同的dataloader。



-----原始邮件-----
发件人:sunqimin ***@***.***>
发送时间:2024-12-18 17:26:31 (星期三)
收件人: MIV-XJTU/ARTrack ***@***.***>
抄送: "Yifan Bai" ***@***.***>, "State change" ***@***.***>
主题: Re: [MIV-XJTU/ARTrack] No coco (Issue #90)






我的问题依然没有解决，我猜是loader的原因，因为数据是一样的，而第一阶段和第二阶段不一样的地方就在于这里，所以请问为什么第一阶段和第二阶段的loader不一样呢
