### ISSUE TITLE
ARTrack第二阶段训练报错

### ISSUE THREAD

**Issue by syudx** [MIV-XJTU/ARTrack#99]
最近我在复现ARTrack的代码，我在尝试第一阶段训练时，训练了两个epoch未出错，于是尝试第二阶段的训练，将下载的‘ARTrack_ep0240.pth.tar’放在了指定文件夹下，在相应的yaml文件中也添加了相应路径，但运行后提示如下错误：
Traceback (most recent call last):
  File "E:\ARTrack-main\lib\train\../..\lib\train\trainers\base_trainer.py", line 85, in train
    self.train_epoch()
  File "E:\ARTrack-main\lib\train\../..\lib\train\trainers\ltr_seq_trainer.py", line 227, in train_epoch
    self.cycle_dataset(loader)
  File "E:\ARTrack-main\lib\train\../..\lib\train\trainers\ltr_seq_trainer.py", line 79, in cycle_dataset
    for i, data in enumerate(loader, 1):
  File "D:\anaconda3\envs\artrack\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "D:\anaconda3\envs\artrack\lib\site-packages\torch\utils\data\dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "D:\anaconda3\envs\artrack\lib\site-packages\torch\utils\data\dataloader.py", line 1250, in _process_data
    data.reraise()
  File "D:\anaconda3\envs\artrack\lib\site-packages\torch\_utils.py", line 457, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda3\envs\artrack\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda3\envs\artrack\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\envs\artrack\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\ARTrack-main\lib\train\../..\lib\train\data\sequence_sampler.py", line 245, in __getitem__
    template_frames, template_anno, meta_obj_template = dataset.get_frames(seq_id, template_frame_ids, seq_info_dict)
  File "E:\ARTrack-main\lib\train\../..\lib\train\dataset\lasot.py", line 153, in get_frames
    obj_class = self._get_class(seq_path)
  File "E:\ARTrack-main\lib\train\../..\lib\train\dataset\lasot.py", line 141, in _get_class
    raw_class = seq_path.split('/')[-2]
IndexError: list index out of range

Restarting training from last epoch ...
Finished training!真诚地希望您能解答一下，这个是什么原因造成的，有什么方法可以改正一下。

**Comment by AlexDotHam** [comment]
我猜測是因爲這個代碼是針對linux系統設計的代碼尋址，使用windows會存在一些問題，您可以嘗試一下將：raw_class = seq_path.split('/')[-2] 修改爲： raw_class = seq_path.split('\')[-2]，因爲windows使用正斜杠來區分路徑。

**Comment by syudx** [comment]
> 我猜測是因爲這個代碼是針對linux系統設計的代碼尋址，使用windows會存在一些問題，您可以嘗試一下將：raw_class = seq_path.split('/')[-2] 修改爲： raw_class = seq_path.split('')[-2]，因爲windows使用正斜杠來區分路徑。

感谢您这么及时的回复，我改成了raw_class = seq_path.split('//')[-2]，问题已经解决。祝您工作顺利。
